Esqueleto para los pilares
GWP01/about_us pull request #7
Opened 2020-04-12 23:40 UTC by leonfhl

Se propone esta v0.1 para empezar a definir los pilares

2020-04-14 22:56 UTC, srcolinas requested changes

2020-04-14 22:56 UTC, srcolinas commented on pilares.md
> +- Pensamiento lógico:
Sería bueno que cada uno de los items tuviera una explicación, así como lo tienen `Propósito sostenibles` y `Pensamiento crítico y solución de problemas` (que por cierto deberían ser dos cosas separadas)

2020-04-14 22:56 UTC, srcolinas commented on pilares.md
> +- Pensamiento crítico y solución de problemas: Los aprendices consideran varias alternativas y reconocen patrones que les ayudan a resolver problemas empleando metodos que les permitan cada vez llega
Yo digo que una cosa es Pensamiento crítico y otra es Solución de problemas, por qué están juntos acá? nno cres que es mejor separados?

2020-04-14 22:57 UTC, srcolinas requested changes

2020-04-14 22:57 UTC, srcolinas commented on pilares.md
> +PILARES
I do not like capital letters here

2020-04-15 01:48 UTC, leonfhl commented on pilares.md
> +- Pensamiento lógico:
Si, por eso es version 0.1: Para que alguien más hiciera esa parte, pero lo reviso con andrea y lo completamos

2020-04-15 01:52 UTC, leonfhl commented on pilares.md
> +- Pensamiento crítico y solución de problemas: Los aprendices consideran varias alternativas y reconocen patrones que les ayudan a resolver problemas empleando metodos que les permitan cada vez llega
Normalmente siempre estan agrupados, pero tal vez si sea mejor separarlos.

2020-05-31 01:00 UTC, closed without merging